name: CD Pipeline

on:
    workflow_run:
        workflows: ['CI Pipeline']
        types:
            - completed

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - name: Pull Docker image
              run: docker push zuzavonpizza/wtum:latest
            - name: Delete Old docker container
              run: sudo docker rm -f wtum-container || true
            - name: Run Docker Container
              run: sudo docker run -d -p 8080:8080 --name wtum-container zuzannavonpizza/wtum:latest

