name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types: ['completed']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/wtum:latest
      - name: Delete Old docker container
        run: sudo docker rm -f wtum-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name wtum-container ${{ secrets.DOCKER_USERNAME }}/wtum:latest
